## Statistical Tests to select the best k Features using the selectKBest Module
-  ANOVA F-value, f_classif (classification)
-  Chi-squared stats of non-negative features, chi2 (classification)
-  F-value, f_regression (regression)
- Mutual information for a continuous target, mutual_info_regression (regression)

In [2]:
from sklearn import datasets
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [3]:
data = datasets.load_iris()

# Seperte features and target 
X = data.data
y = data.target



In [4]:
# display first 5 rows
X[0:5,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [5]:
# features engineering, Let's see the best 3 features by setting k =3
KBest_chi = SelectKBest(score_func=chi2,k=3)
fit_test = KBest_chi.fit(X,y)
fit_test.scores_

array([ 10.81782088,   3.7107283 , 116.31261309,  67.0483602 ])

## Recursive Feature Elimination (RFE)

In [9]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
from sklearn import datasets

data = datasets.load_boston()

X = data.data
y = data.target

linear_reg = LinearRegression()
rfe = RFE(estimator=linear_reg,n_features_to_select=6)
rfe_fit = rfe.fit(X,y)
rfe_fit.ranking_


/Users/ngounepeetprogress/opt/anaconda3/envs/deepL/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets incl

array([3, 5, 4, 1, 1, 1, 8, 1, 2, 6, 1, 7, 1])